---
title: "Explore datasets"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("osmdata")
library(osmdata)
#install.packages('Rcpp')
library(tidyverse)
library(tmap)
library(ggplot2)
library(ggthemes)
library(patchwork)
library(sf)
#install.packages("sfnetworks")
library(sfnetworks)
library(janitor)
library(htmlTable)

```


From paper: Urban access across the globe: An international comparison of different transport modes. Npj Urban Sustainability, 1(1), 1–9. https://doi.org/10.1038/s42949-021-00020-2  

Data URL: https://springernature.figshare.com/articles/dataset/Metadata_record_for_the_manuscript_Urban_Access_Across_the_Globe_An_International_Comparison_of_Different_Transport_Modes/13476867?file=25865205
```{r}
library(readr)
allcities <- read_delim("data/AllCities-Urban access across the globe.csv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)
```

```{r}
allcities %>%
  group_by(Country) %>%
  count() %>%
  adorn_totals("row") %>%
  knitr::kable("rst")
```

```{r}
names(allcities) %>%
  as.vector() %>%
  cat(sep = ", ")
```

